kind: Service
apiVersion: v1
metadata:
  name: nginx-myapp-nodeport
  labels:
    app: testapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033
  selector:
    app: testapp
  type: NodePort
