---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      name: my-app
      labels:
        app: testapp
    spec:
      containers:
        - name: my-testapp-nginx
          image: "{{- .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
