---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: testapp
  name: myapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033
  selector:
    app: testapp
  type: NodePort
