name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: AleksandrOdintsov/nginx
          path: nginx

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/Dockerfile
          push: true
          tags: docker.io/aleksandrodintsov/nginx:${{ github.ref_name }}
          secrets: |
            github.token=${{ secrets.GITHUB_TOKEN }}
            dockerhub_token=${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: AleksandrOdintsov/myapp
          path: myapp

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1.3
        with:
          manifests: |
            myapp/templates/*
          images: docker.io/aleksandrodintsov/nginx:${{ github.ref_name }}
          values-files: myapp/values.yaml
          kubectl-version: "latest"
