name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Git tag
        id: git_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Update index.html with version
        run: |
          echo "<!DOCTYPE html>
          <html>
          <head>
              <title>My Test App</title>
          </head>
          <body>
              <h1>Welcome to My Test App!</h1>
              <p>This is a simple static website.</p>
              <p>Version: ${{ steps.git_tag.outputs.tag }}</p>
          </body>
          </html>" > index.html

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add index.html
          git commit -m "Update index.html with version: ${{ steps.git_tag.outputs.tag }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  deploy:
    needs: update-index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "latest"

      - name: Upgrade Helm Chart
        run: helm upgrade --install myapp ./ -f ./values.yaml
