name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: docker.io/aleksandrodintsov/myapp
          tags: latest
        if: github.event_name == 'push'

      - name: Build, tag, and push Docker image on release
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: docker.io/aleksandrodintsov/myapp
          tags: v${{ github.event.release.tag_name }}
        if: github.event_name == 'release'

      - name: Update tag in values.yaml
        run: |
          sed -i 's/tag: ".*"/tag: "v${{ github.event.release.tag_name }}"/' ./values.yaml
        if: github.event_name == 'release'

      - name: Deploy to Kubernetes
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.KUBE_CONFIG }}
          cluster-name: my-cluster
          resource-group: my-resource-group
        if: github.event_name == 'release'

      - name: Helm upgrade
        run: |
          helm upgrade --install myapp ./ -f ./values.yaml
        if: github.event_name == 'release'
