name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          docker build -t myapp:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with tag
        if: ${{ github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker build -t myapp:${{ github.ref }} .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push Docker image
        run: |
          docker tag myapp:latest docker.io/aleksandrodintsov/nginx:latest
          docker push docker.io/aleksandrodintsov/nginx:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-tagged:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push Docker image with tag
        if: ${{ github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker tag myapp:${{ github.ref }} docker.io/aleksandrodintsov/nginx:${{ github.ref }}
          docker push docker.io/aleksandrodintsov/nginx:${{ github.ref }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: push-tagged
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Update Helm Chart values
        run: |
          sed -i "s/tag: '.*'/tag: '${{ github.ref }}'/" ./values.yaml

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install myapp ./ -f ./values.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
