name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit tag
        id: tag
        run: echo ::set-output name=TAG::$(git tag --points-at $GITHUB_SHA)

      - name: Build Docker image
        run: docker build -t myapp:${{ steps.tag.outputs.TAG }} .
      
      - name: Tag Docker image
        run: docker tag myapp:${{ steps.tag.outputs.TAG }} myapp:${{ steps.tag.outputs.TAG }}

      - name: Push Docker image
        run: docker push myapp:${{ steps.tag.outputs.TAG }}

  update_values_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit tag
        id: tag
        run: echo ::set-output name=TAG::$(git tag --points-at $GITHUB_SHA)

      - name: Update tag in values.yaml
        run: sed -i "s/tag: \".*\"/tag: \"${{ steps.tag.outputs.TAG }}\"/" ./values.yaml

      - name: Deploy to Kubernetes
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.KUBE_CONFIG }}
          cluster-name: my-cluster
          resource-group: my-resource-group
      
      - name: Helm upgrade
        run: helm upgrade --install myapp ./ -f ./values.yaml
