name: CI/CD

on:
  push:
    branches:
      - main
      - "v*" # Срабатывает на создание тегов, начинающихся с 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Docker image tag
        id: tag
        run: echo "::set-output name=TAG::$(echo $GITHUB_SHA | head -c 7)"

      - name: Change Docker image tag
        run: |
          docker tag docker.io/***/nginx:${{ steps.tag.outputs.TAG }} docker.io/***/nginx:${{ steps.tag.outputs.TAG }}
          docker push docker.io/***/nginx:${{ steps.tag.outputs.TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Update values.yaml
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ steps.tag.outputs.TAG }}\"/" ./values.yaml

      - name: Deploy to Kubernetes
        run: helm upgrade --install myapp ./ -f ./values.yaml
