name: Ci-CD

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/username/image:latest . --push

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Extract tag
        id: extract_tag
        run: echo ::set-output name=tag::$(echo "${GITHUB_REF##*/}")

      - name: Update values.yaml
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ needs.build-and-push.outputs.TAG }}\"/" ./values.yaml

      - name: Deploy to Kubernetes
        run: helm upgrade --install myapp ./ -f ./values.yaml
