name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Docker image tag
        id: tag
        run: echo "::set-output name=TAG::$(echo $GITHUB_REF | sed 's/refs\/tags\///')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/aleksandrodintsov/nginx:${{ steps.tag.outputs.TAG }} .
          docker push docker.io/aleksandrodintsov/nginx:${{ steps.tag.outputs.TAG }}

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Update values.yaml
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ steps.tag.outputs.TAG }}\"/" ./values.yaml

      - name: Deploy to Kubernetes
        run: helm upgrade --install myapp ./ -f ./values.yaml
