name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag from commit
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/***/nginx:${{ steps.tag.outputs.TAG }} .
          docker push docker.io/***/nginx:${{ steps.tag.outputs.TAG }}

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Update values.yaml
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ steps.tag.outputs.TAG }}\"/" ./values.yaml

      - name: Deploy to Kubernetes
        run: helm upgrade --install myapp ./ -f ./values.yaml
