name: CI/CD

on:
  push:
    tags:
      - "v*.*.*" # Триггер на создание тега, например, v1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: extract-tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t myapp:${{ env.TAG }} .
          docker tag myapp:${{ env.TAG }} ${DOCKER_USERNAME}/myapp:${{ env.TAG }}
          docker push ${DOCKER_USERNAME}/myapp:${{ env.TAG }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.30.2"

      - name: Deploy to Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          helm upgrade --install myapp ./ -f ./values.yaml --set image.repository=${DOCKER_USERNAME}/myapp --set image.tag=${{ env.TAG }}
