name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/nginx:latest .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/nginx:latest

  tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image with tag
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/nginx:${{ env.tag }} .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/nginx:${{ env.tag }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl with Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Validate Kubernetes context
        run: kubectl config current-context

      - name: Update values.yaml
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ env.tag }}\"/" ./values.yaml

      - name: Deploy to Kubernetes
        run: helm upgrade --install myapp ./ -f ./values.yaml
